void main() {
  String ilce = "Çekmeköy";
  print("İlçe : $ilce");
  String kita = "Asya";
  print("Kita : $kita");
  String faks = "+90 212 123 45 67";
  print("Faks : $faks");
  int postaKodu = 34788;
  print("Posta Kodu : $postaKodu");
  String instaAdresi = "@enessodbs";
  print("İnstagram : $instaAdresi");
  String calistigiBolum = "Yazılım";
  print("Çalıştığı Bölüm : $calistigiBolum");
  int urunMiktari = 100;
  print("Ürün Miktarı : $urunMiktari");
  String musteriSoyad = "Odabaş";
  print("Müşteri Soyad : $musteriSoyad");
  double odemeMiktari = 999.99;
  print("Ödeme Miktarı : $odemeMiktari");
  String dogumTarihi = "03.12.2000";
  print("Doğum Tarihi : $dogumTarihi");
  double borc = 150.50;
  print("Borç : $borc");
  String medeniHal = "Bekar";
  print("Medeni Hal : $medeniHal");
  String yorum = "Flutter Dersleri";
  print("Yorum : $yorum");
  String odemeSaati = "19:07";
  print("Ödeme Saati : $odemeSaati");
  double eftMiktari = 1907.19;
  print("EFT Miktarı : $eftMiktari");
  int satilanMiktar = 1907;
  print("Satılan Miktar : $satilanMiktar");
  String telefonModeli = "Samsung Galaxy S20";
  print("Telefon Modeli : $telefonModeli");
  String dergiAdi = "Flutter";
  print("Dergi Adı : $dergiAdi");
  String basimTarihi = "19.07.2024";
  print("Basım Tarihi : $basimTarihi");
  double zamMiktari = 1907.19;
  print("Zam Miktarı : $zamMiktari");
  int daireSayisi = 10;
  print("Daire Sayısı : $daireSayisi");
  String enlem = "36° ile 42° kuzey enlemleri";
  print("Enlem : $enlem");
  String boylam = "26° ile 45° doğu";
  print("Boylam : $boylam");
  String yemekAdi = "Tavuk Pilav";
  print("Yemek Adı : $yemekAdi");
  double urunFiyati = 1907;
  print("Ürün Fiyatı : $urunFiyati");
  String sirketAdi = "Tech Career";
  print("Şirket Adı : $sirketAdi");
  String videoAdi = "Flutter BootCamp Dersleri";
  print("Video Adı : $videoAdi");
  double muzikSuresi = 5.45;
  print("Müzik Süresi : $muzikSuresi");
  double mekanPuani = 4.5;
  print("Mekan Puanı : $mekanPuani");
  String dosyaAdi = "image/pp.png";
  print("Dosya Adı : $dosyaAdi");
  String resimFormati = "png";
  print("Resim Formatı : $resimFormati");
  String renk = "mavi";
  print("Renk : $renk");
  String bilgisayarModeli = "Abra A5";
  print("Bilgisayar Modeli : $bilgisayarModeli");
  String ekranBoyutu = "15.6 inç";
  print("Ekran Boyutu : $ekranBoyutu");
  String kullanimSuresi = "15 gün";
  print("Kullanım Süresi : $kullanimSuresi");
  String basinc = "1015 hPa";
  print("Basınç : $basinc");
  String etkinlikGunu = "Perşembe";
  print("Etkinlik Günü : $etkinlikGunu");
  String odemeGunu = "Salı";
  print("Ödeme Günü : $odemeGunu");
  String yolculukCikisTarihi = "19.07.2024";
  print("Yolculuk Tarihi : $yolculukCikisTarihi");
  String mahalleAdi = "Soğukpınar";
  print("Mahalle Adı : $mahalleAdi");
  String otobusHatti = "131T";
  print("Otobüs Hattı : $otobusHatti");
  double kullanilanDakika = 19.07;
  print("Kullanılan Dakika : $kullanilanDakika");
  String kargoTakipNo = "TR1234567890XX";
  print("Kargo Takip No : $kargoTakipNo");
  String kuponSuresi = "5 gün";
  print("Kupon Süresi : $kuponSuresi");
  String kuponKodu = "SAVE20OFFNOW";
  print("Kupon Kodu : $kuponKodu");
  String faturaTarihi = "19.07.2024";
  print("Fatura Tarihi : $faturaTarihi");
}
